name: Style dictionary build

on:
  push:
    paths:
      - 'config.json'
    branches-ignore:
      - 'main'
  workflow_run:
    workflows:
      - "Transform tokens using token-transformer"
    types:
      - "completed"
    branches-ignore:
    - 'main'

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Node Dependencies
        run: npm install
      - name: Run style dictionary build
        run: npm run build
      - name: Commit built tokens
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated design tokens
